[package]
name = "digit_recognizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.93"
csv = "1.3.0"
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
